import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { Skeleton } from "@/components/ui/skeleton";
import { api } from "@/lib/api/client";
import {
  capabilitiesQuery,
  documentsQuery,
  ErrorState,
  KV,
  Mono,
  PageHeader,
  Panel,
  Tag,
} from "@/components/rag/common";
import { loadStoredReport, type StoredReport } from "@/lib/eval-report";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Workspace overview — RAGForge" },
      {
        name: "description",
        content:
          "Index status, provider mode and latest evaluation run for your RAGForge workspace.",
      },
      { property: "og:title", content: "Workspace overview — RAGForge" },
      {
        property: "og:description",
        content:
          "Index status, provider mode and latest evaluation run for your RAGForge workspace.",
      },
    ],
  }),
  component: Overview,
});

function Stat({
  label,
  value,
  loading,
  note,
}: {
  label: string;
  value: React.ReactNode;
  loading?: boolean | undefined;
  note?: string | undefined;
}) {
  return (
    <div className="rounded-md border bg-card p-4">
      <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{label}</p>
      {loading ? (
        <Skeleton className="mt-2 h-7 w-20" />
      ) : (
        <p className="mt-1 font-mono text-2xl font-semibold">{value}</p>
      )}
      {note && <p className="mt-1 text-xs text-muted-foreground">{note}</p>}
    </div>
  );
}

function Overview() {
  const caps = useQuery(capabilitiesQuery);
  const docs = useQuery(documentsQuery);
  const ready = useQuery({ queryKey: ["ready"], queryFn: api.ready, retry: 0 });
  const [report, setReport] = useState<StoredReport | null>(null);
  useEffect(() => setReport(loadStoredReport()), []);

  const chunkCounts = docs.data?.map((d) => d.chunk_count);
  const chunks =
    chunkCounts && chunkCounts.every((c) => c != null)
      ? chunkCounts.reduce((a, b) => a + (b ?? 0), 0)
      : undefined;
  const provider = caps.data?.provider_configured === true;

  return (
    <>
      <PageHeader
        title="Workspace overview"
        description="Current index, generation mode and evaluation state. All values come from the API; nothing here is estimated."
      />
      {(caps.isError || docs.isError) && (
        <div className="mb-4">
          <ErrorState
            error={caps.error ?? docs.error}
            onRetry={() => {
              caps.refetch();
              docs.refetch();
            }}
          />
        </div>
      )}
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <Stat label="Documents" value={docs.data?.length ?? "—"} loading={docs.isLoading} />
        <Stat
          label="Chunks"
          value={chunks ?? "—"}
          loading={docs.isLoading}
          note={chunks == null && docs.isSuccess ? "Not reported by API" : undefined}
        />
        <Stat
          label="Default retrieval"
          value={caps.data?.default_retrieval_mode ?? "—"}
          loading={caps.isLoading}
          note={
            caps.data?.retrieval_modes
              ? `available: ${caps.data.retrieval_modes.join(", ")}`
              : undefined
          }
        />
        <Stat
          label="Readiness"
          value={ready.isSuccess ? "ready" : ready.isError ? "not ready" : "…"}
          loading={ready.isLoading}
        />
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-2">
        <Panel title="Generation mode">
          {caps.isLoading ? (
            <Skeleton className="h-16" />
          ) : caps.isSuccess ? (
            <div className="space-y-2 text-sm">
              <div className="flex items-center gap-2">
                <Tag tone={provider ? "primary" : "warning"}>
                  {provider ? "provider-backed" : "offline extractive"}
                </Tag>
                {caps.data.provider && <Mono>{String(caps.data.provider)}</Mono>}
              </div>
              <p className="text-muted-foreground">
                {provider
                  ? "Answers are generated by the configured model provider from retrieved evidence. Query rewrite and HyDE are available."
                  : "No model provider is configured. Answers are extracted verbatim from retrieved chunks; rewrite and HyDE are unavailable. The system abstains when evidence is insufficient."}
              </p>
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">Unavailable.</p>
          )}
        </Panel>
        <Panel
          title="Latest evaluation run"
          aside={
            <Link to="/evaluation" className="text-xs font-medium text-primary hover:underline">
              Open →
            </Link>
          }
        >
          {report ? (
            (() => {
              const firstRun =
                Array.isArray(report.runs) && report.runs[0] && typeof report.runs[0] === "object"
                  ? (report.runs[0] as Record<string, unknown>)
                  : null;
              const runId = String(report.run_id ?? firstRun?.run_id ?? "—");
              const ts = String(report.timestamp ?? report.created_at ?? "no timestamp");
              return (
                <div className="space-y-1 text-sm">
                  <p>
                    Run <Mono>{runId}</Mono>
                  </p>
                  <p className="text-xs text-muted-foreground">
                    {ts} · loaded locally from report file “{report._filename}”
                  </p>
                </div>
              );
            })()
          ) : (
            <p className="text-sm text-muted-foreground">
              The API has no evaluation endpoint. Load a report JSON produced by the RAGForge
              evaluation CLI on the Evaluation page to see it here.
            </p>
          )}
        </Panel>
        <Panel title="Capabilities (raw)" className="lg:col-span-2">
          {caps.isLoading ? <Skeleton className="h-24" /> : <KV data={caps.data} />}
        </Panel>
      </div>
    </>
  );
}
