/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as ApiRagSplatRouteImport } from './routes/api/rag.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagSplatRoute = ApiRagSplatRouteImport.update({
  id: '/api/rag/$',
  path: '/api/rag/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/documents': typeof DocumentsRoute
  '/evaluation': typeof EvaluationRoute
  '/inspector': typeof InspectorRoute
  '/api/rag/$': typeof ApiRagSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/documents': typeof DocumentsRoute
  '/evaluation': typeof EvaluationRoute
  '/inspector': typeof InspectorRoute
  '/api/rag/$': typeof ApiRagSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/documents': typeof DocumentsRoute
  '/evaluation': typeof EvaluationRoute
  '/inspector': typeof InspectorRoute
  '/api/rag/$': typeof ApiRagSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ask' | '/documents' | '/evaluation' | '/inspector' | '/api/rag/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask' | '/documents' | '/evaluation' | '/inspector' | '/api/rag/$'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/documents'
    | '/evaluation'
    | '/inspector'
    | '/api/rag/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  DocumentsRoute: typeof DocumentsRoute
  EvaluationRoute: typeof EvaluationRoute
  InspectorRoute: typeof InspectorRoute
  ApiRagSplatRoute: typeof ApiRagSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/$': {
      id: '/api/rag/$'
      path: '/api/rag/$'
      fullPath: '/api/rag/$'
      preLoaderRoute: typeof ApiRagSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  DocumentsRoute: DocumentsRoute,
  EvaluationRoute: EvaluationRoute,
  InspectorRoute: InspectorRoute,
  ApiRagSplatRoute: ApiRagSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
